FROM openjdk:8-jre-alpine
VOLUME /tmp
ADD ./build/libs/sprint-0.0.1-SNAPSHOT.jar app.jar
RUN sh -c 'touch /app.jar'
ENV JAVA_OPTS=""
ENTRYPOINT [ "/bin/sh", "-c" , "echo 127.0.0.1 $HOSTNAME >> /etc/hosts" ]
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]